AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to provision a Lambda function and IAM roles for querying Bedrock Claude model.

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project (used for resource naming)
    Default: "bedrock-quiz"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "Must contain only lowercase letters, numbers, and hyphens"

  Environment:
    Type: String
    Description: Environment name (prod, dev, staging)
    Default: "prod"
    AllowedValues: ["prod", "dev", "staging"]

  DomainName:
    Type: String
    Description: Your custom domain name (e.g., yourdomain.com)
    Default: "hexmi.com"

  SubdomainName:
    Type: String
    Description: Subdomain for the quiz app (e.g., quiz, dev-quiz)
    Default: "quiz"

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for your domain
    Default: "Z01335492T06E59B8E8ZZ" # Your hexmi.com hosted zone ID

  SSLCertificateArn:
    Type: String
    Description: SSL Certificate ARN from us-east-1 (optional)
    Default: ""

  LambdaTimeout:
    Type: Number
    Description: Lambda function timeout in seconds
    Default: 15
    MinValue: 1
    MaxValue: 900

  LambdaMemory:
    Type: Number
    Description: Lambda function memory in MB
    Default: 128
    AllowedValues: [128, 256, 512, 1024, 2048, 3072]

Conditions:
  UseCustomDomain: !Not [!Equals [!Ref HostedZoneId, ""]]
  IsProduction: !Equals [!Ref Environment, "prod"]
  HasExternalSSLCert: !Not [!Equals [!Ref SSLCertificateArn, ""]]

Resources:
  # NOTE: SSL Certificate is deployed separately in us-east-1 via GitHub Actions
  # This template references the external SSL certificate via parameter

  # S3 Bucket for Frontend Hosting
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3600

  # S3 Bucket Policy (MOST RELIABLE)
  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: FrontendS3Bucket
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Ref FrontendS3Bucket
                  - "/*"
          - Sid: PublicListBucket
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:ListBucket"
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Ref FrontendS3Bucket

  # IAM Role for Lambda Function
  BedrockQueryLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bedrock-query-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock2/*"

  # Lambda Function
  BedrockQueryLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-backend"
      Runtime: nodejs20.x
      Handler: src/handlers/queryBedrock.handler
      Role: !GetAtt BedrockQueryLambdaRole.Arn
      Code:
        S3Bucket: my-lambda-deployment-bucket-for-bedrock2
        S3Key: function.zip
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemory
      Environment:
        Variables:
          BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
          ENVIRONMENT: !Ref Environment
          PROJECT_NAME: !Ref ProjectName

  # API Gateway REST API
  BedrockQuizApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: bedrock-quiz-api
      Description: API Gateway for Bedrock Quiz Lambda function
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource
  QuizResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      ParentId: !GetAtt BedrockQuizApiGateway.RootResourceId
      PathPart: quiz

  # API Gateway Method (POST)
  QuizMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      ResourceId: !Ref QuizResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BedrockQueryLambdaFunction.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false # ← Must be uppercase 'M'

  # API Gateway Method (OPTIONS for CORS)
  QuizMethodOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      ResourceId: !Ref QuizResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false # ← Must be uppercase 'M'

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - QuizMethodPost
      - QuizMethodOptions
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      StageName: prod

  # Lambda Permission for API Gateway
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BedrockQueryLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BedrockQuizApiGateway}/*/*"

  # CloudFront Distribution (Updated to use external SSL certificate)
  FrontendCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - FrontendS3Bucket
      - FrontendS3BucketPolicy
    Properties:
      DistributionConfig:
        Aliases: !If
          - HasExternalSSLCert
          - !If
            - IsProduction
            - [!Ref DomainName, !Sub "${SubdomainName}.${DomainName}"] # Both hexmi.com and quiz.hexmi.com
            - [!Sub "${SubdomainName}.${DomainName}"] # Only quiz.hexmi.com for dev
          - !Ref AWS::NoValue
        Comment: !Sub "CloudFront distribution for ${AWS::StackName}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendS3Bucket.RegionalDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
        ViewerCertificate: !If
          - HasExternalSSLCert
          - AcmCertificateArn: !Ref SSLCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Route 53 DNS Records
  DNSRecordMain:
    Type: AWS::Route53::RecordSet
    Condition: HasExternalSSLCert  # Only create if we have SSL certificate
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName # hexmi.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt FrontendCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DNSRecordSubdomain:
    Type: AWS::Route53::RecordSet
    Condition: HasExternalSSLCert  # Only create if we have SSL certificate
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${SubdomainName}.${DomainName}" # quiz.hexmi.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt FrontendCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref BedrockQueryLambdaFunction

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt BedrockQueryLambdaFunction.Arn

  ApiGatewayUrl:
    Description: API Gateway endpoint URL for the quiz function
    Value: !Sub "https://${BedrockQuizApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/quiz"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayUrl"

  FrontendS3BucketName:
    Description: Name of the S3 bucket for frontend hosting
    Value: !Ref FrontendS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-FrontendS3BucketName"

  FrontendS3BucketWebsiteURL:
    Description: S3 bucket website URL for the frontend
    Value: !GetAtt FrontendS3Bucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-FrontendS3BucketWebsiteURL"

  FrontendCloudFrontURL:
    Description: CloudFront distribution URL for the frontend
    Value: !Sub "https://${FrontendCloudFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-FrontendCloudFrontURL"

  CustomDomainURL:
    Description: Custom domain URL (if SSL certificate is configured)
    Condition: HasExternalSSLCert
    Value: !Sub "https://${SubdomainName}.${DomainName}"

  SSLCertificateArn:
    Description: SSL Certificate ARN (if provided)
    Condition: HasExternalSSLCert
    Value: !Ref SSLCertificateArn

  FrontendCloudFrontDistributionId:
    Description: CloudFront distribution ID for cache invalidation
    Value: !Ref FrontendCloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-FrontendCloudFrontDistributionId"
