AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to provision a Lambda function and IAM roles for querying Bedrock Claude model.

Resources:
  # IAM Role for Lambda Function
  BedrockQueryLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bedrock-query-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock/*"

  # Lambda Function
  BedrockQueryLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: bedrock-query
      Runtime: nodejs20.x # Updated to use Node.js 20
      Handler: src/handlers/queryBedrock.handler
      Role: !GetAtt BedrockQueryLambdaRole.Arn
      Code:
        S3Bucket: my-lambda-deployment-bucket-for-bedrock
        S3Key: function.zip # The zip file uploaded to the bucket
      Timeout: 15
      MemorySize: 128
      Environment:
        Variables:
          BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0 # Replace with your actual model ID

  # IAM Role for GitHub Actions Deployment
  DeploymentIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-deployment-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDeploymentPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                  - lambda:GetFunctionConfiguration
                Resource: "arn:aws:lambda:*:*:function:bedrock-query"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock"
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock/*"

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref BedrockQueryLambdaFunction

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt BedrockQueryLambdaFunction.Arn
