AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to provision a Lambda function and IAM roles for querying Bedrock Claude model.

Resources:
  # IAM Role for Lambda Function
  BedrockQueryLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bedrock-query-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock2/*"

  # Lambda Function
  BedrockQueryLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: bedrock-query
      Runtime: nodejs20.x # Updated to use Node.js 20
      Handler: src/handlers/queryBedrock.handler
      Role: !GetAtt BedrockQueryLambdaRole.Arn
      Code:
        S3Bucket: my-lambda-deployment-bucket-for-bedrock2 # Updated bucket name
        S3Key: function.zip # The zip file uploaded to the bucket
      Timeout: 15
      MemorySize: 128
      Environment:
        Variables:
          BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0 # Replace with your actual model ID

  # API Gateway REST API
  BedrockQuizApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: bedrock-quiz-api
      Description: API Gateway for Bedrock Quiz Lambda function
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource
  QuizResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      ParentId: !GetAtt BedrockQuizApiGateway.RootResourceId
      PathPart: quiz

  # API Gateway Method (POST)
  QuizMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      ResourceId: !Ref QuizResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BedrockQueryLambdaFunction.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false

  # API Gateway Method (OPTIONS for CORS)
  QuizMethodOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      ResourceId: !Ref QuizResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - QuizMethodPost
      - QuizMethodOptions
    Properties:
      RestApiId: !Ref BedrockQuizApiGateway
      StageName: prod

  # Lambda Permission for API Gateway
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BedrockQueryLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BedrockQuizApiGateway}/*/*"

  # IAM Role for GitHub Actions Deployment
  DeploymentIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-deployment-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDeploymentPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                  - lambda:GetFunctionConfiguration
                Resource: "arn:aws:lambda:*:*:function:bedrock-query"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock2"
                  - "arn:aws:s3:::my-lambda-deployment-bucket-for-bedrock2/*"
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                Resource: "*"

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref BedrockQueryLambdaFunction

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt BedrockQueryLambdaFunction.Arn

  ApiGatewayUrl:
    Description: API Gateway endpoint URL for the quiz function
    Value: !Sub "https://${BedrockQuizApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/quiz"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayUrl"
