name: Deploy Lambda Function and CloudFormation Stack

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Navigate to backend folder and install dependencies
      - name: Install dependencies
        working-directory: backend
        run: npm install

      # Step 4: Debug AWS CLI Configuration
      - name: Debug AWS CLI Configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure list

      # Step 5: Zip the Lambda function code
      - name: Zip Lambda function
        working-directory: backend
        run: zip -r function.zip . -x "*.git*" "node_modules/aws-sdk/*"

      # Step 6: Upload the zip file to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: backend
        run: |
          aws s3 cp function.zip s3://my-lambda-deployment-bucket-for-bedrock2/function.zip

      # Step 6.5: Handle rollback state (MOVED BEFORE DEPLOY)
      - name: Handle stack rollback state
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "🔍 Checking stack status..."

          STATUS=$(aws cloudformation describe-stacks \
            --stack-name bedrock-query-stack \
            --region ${{ secrets.AWS_REGION }} \
            --query 'Stacks[0].StackStatus' \
            --output text 2>/dev/null || echo "STACK_NOT_EXISTS")

          echo "Current stack status: $STATUS"

          if [[ "$STATUS" == *"ROLLBACK_COMPLETE"* ]] || [[ "$STATUS" == *"FAILED"* ]]; then
            echo "⚠️ Stack is in failed state: $STATUS"
            echo "🗑️ Deleting failed stack..."
            aws cloudformation delete-stack \
              --stack-name bedrock-query-stack \
              --region ${{ secrets.AWS_REGION }}
            
            echo "⏳ Waiting for stack deletion (this may take 2-5 minutes)..."
            aws cloudformation wait stack-delete-complete \
              --stack-name bedrock-query-stack \
              --region ${{ secrets.AWS_REGION }}
            
            echo "✅ Failed stack deleted. Ready for fresh deployment."
          elif [[ "$STATUS" == "STACK_NOT_EXISTS" ]]; then
            echo "✅ No existing stack found. Ready for fresh deployment."
          else
            echo "✅ Stack is in good state: $STATUS"
          fi

      # Step 7: Deploy CloudFormation Stack (NOW RUNS AFTER CLEANUP)
      - name: Deploy CloudFormation Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: infrastructure
        run: |
          echo "🚀 Deploying CloudFormation stack..."

          # Deploy the stack with a longer timeout
          aws cloudformation deploy \
            --template-file bedrock-query-template.yaml \
            --stack-name bedrock-query-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --no-fail-on-empty-changeset \
            || echo "Deploy command completed with warnings"

          echo "⏳ Ensuring stack is in a stable state..."

          # Wait for the stack to be in a complete state
          for i in {1..20}; do  # Increased from 10 to 20 attempts
            STATUS=$(aws cloudformation describe-stacks \
              --stack-name bedrock-query-stack \
              --region ${{ secrets.AWS_REGION }} \
              --query 'Stacks[0].StackStatus' \
              --output text)
            
            echo "Stack status: $STATUS"
            
            if [[ "$STATUS" == "CREATE_COMPLETE" || "$STATUS" == "UPDATE_COMPLETE" ]]; then
              echo "✅ Stack is ready!"
              break
            elif [[ "$STATUS" == *"FAILED"* || "$STATUS" == *"ROLLBACK"* ]]; then
              echo "❌ Stack deployment failed with status: $STATUS"
              aws cloudformation describe-stack-events \
                --stack-name bedrock-query-stack \
                --region ${{ secrets.AWS_REGION }} \
                --query 'StackEvents[?ResourceStatus==`CREATE_FAILED` || ResourceStatus==`UPDATE_FAILED`].[LogicalResourceId,ResourceStatus,ResourceStatusReason]' \
                --output table
              exit 1
            else
              echo "⏳ Waiting for stack (attempt $i/20)..."
              sleep 30
            fi
          done

      # Step 8: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          echo "📦 Installing frontend dependencies..."
          npm install

      # Step 9: Build frontend
      - name: Build frontend
        working-directory: frontend
        run: |
          echo "🏗️ Building React frontend..."
          npm run build
          echo "📁 Checking build output..."
          ls -la build/
          if [ ! -f "build/index.html" ]; then
            echo "❌ Build failed - index.html not found"
            exit 1
          fi
          echo "✅ Frontend build completed successfully"

      # Step 9.5: Update API endpoint in frontend (NEW)
      - name: Update API endpoint in frontend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: frontend
        run: |
          echo "🔗 Getting API Gateway URL from CloudFormation..."

          API_URL=$(aws cloudformation describe-stacks \
            --stack-name bedrock-query-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
            --output text \
            --region ${{ secrets.AWS_REGION }})

          if [ -z "$API_URL" ] || [ "$API_URL" = "None" ]; then
            echo "❌ Error: API Gateway URL not found in stack outputs"
            exit 1
          fi

          echo "✅ Found API URL: $API_URL"
          echo "🔄 Updating api.js with correct endpoint..."

          # Update the API endpoint in api.js
          sed -i "s|const LAMBDA_ENDPOINT = \".*\";|const LAMBDA_ENDPOINT = \"$API_URL\";|g" src/api.js

          # Verify the change
          echo "📋 Updated api.js content:"
          grep "LAMBDA_ENDPOINT" src/api.js

          echo "✅ API endpoint updated successfully"

      # Step 9.6: Rebuild frontend with updated API endpoint (NEW)
      - name: Rebuild frontend with updated API endpoint
        working-directory: frontend
        run: |
          echo "🏗️ Rebuilding frontend with updated API endpoint..."
          npm run build
          echo "✅ Frontend rebuilt with correct API endpoint"

      # Step 10: Get S3 bucket name from CloudFormation outputs
      - name: Get S3 bucket name
        id: get-bucket-name
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "📋 Getting S3 bucket name..."
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name bedrock-query-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`FrontendS3BucketName`].OutputValue' \
            --output text \
            --region ${{ secrets.AWS_REGION }})

          if [ -z "$BUCKET_NAME" ] || [ "$BUCKET_NAME" = "None" ]; then
            echo "❌ Error: Frontend S3 bucket not found in stack outputs"
            exit 1
          fi

          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "✅ Found S3 bucket: $BUCKET_NAME"

      # Step 11: Deploy frontend to S3
      - name: Deploy frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: frontend
        run: |
          echo "🚀 Deploying frontend to S3..."
          echo "📁 Bucket: ${{ steps.get-bucket-name.outputs.BUCKET_NAME }}"

          # Sync build files to S3
          aws s3 sync build/ s3://${{ steps.get-bucket-name.outputs.BUCKET_NAME }} \
            --delete \
            --cache-control "max-age=31536000" \
            --exclude "*.html" \
            --exclude "service-worker.js"

          # Upload HTML files with no-cache
          aws s3 sync build/ s3://${{ steps.get-bucket-name.outputs.BUCKET_NAME }} \
            --cache-control "no-cache, no-store, must-revalidate" \
            --include "*.html" \
            --include "service-worker.js"

          echo "✅ Frontend deployed to S3"

      # Step 12: Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "🔄 Getting CloudFront distribution ID..."

          DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name bedrock-query-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`FrontendCloudFrontDistributionId`].OutputValue' \
            --output text \
            --region ${{ secrets.AWS_REGION }})

          if [ -z "$DISTRIBUTION_ID" ] || [ "$DISTRIBUTION_ID" = "None" ]; then
            echo "❌ Error: CloudFront distribution ID not found"
            exit 1
          fi

          echo "🔄 Creating CloudFront invalidation..."
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"

          echo "✅ CloudFront invalidation created"
          echo "⏳ Cache invalidation may take 5-15 minutes to complete"

      # Step 13: Display URLs
      - name: Display deployment URLs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "🎉 Deployment completed successfully!"
          echo ""
          echo "📋 Your application URLs:"

          CLOUDFRONT_URL=$(aws cloudformation describe-stacks \
            --stack-name bedrock-query-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`FrontendCloudFrontURL`].OutputValue' \
            --output text \
            --region ${{ secrets.AWS_REGION }})

          API_URL=$(aws cloudformation describe-stacks \
            --stack-name bedrock-query-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
            --output text \
            --region ${{ secrets.AWS_REGION }})

          echo "🌐 Frontend URL: $CLOUDFRONT_URL"
          echo "🔗 API URL: $API_URL"
          echo ""
          echo "⏳ Note: CloudFront cache invalidation may take 5-15 minutes to complete"
